version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login 
      --username AWS --password-stdin public.ecr.aws/n8b0e9r5
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mdono-docke-image .
      - docker tag docker build -t mdono-docke-image:latest public.ecr.aws/n8b0e9r5/aws-codepipeline-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/n8b0e9r5/docker build -t mdono-docke-image:latest

artifacts:
    files: imagedefinitions.json